server:
  port: 8099

eureka:
  client:
    serviceUrl:
      defaultZone: http://209.145.60.40:8761/eureka/

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: spa-service
          uri: https://746d-190-43-38-61.ngrok.io/
          predicates:
            - Path=/spa/**
        - id: desktop-service
          uri: https://49f1-181-64-223-16.ngrok.io/
          predicates:
            - Path=/financiera/**
        - id: movile-service
          uri: lb://movile-service
          predicates:
            - Path=/movile/**
        - id: asp-service
          uri: lb://asp-service
          predicates:
            - Path=/asp/**