server:
  port: 8099

eureka:
  client:
    serviceUrl:
      defaultZone: http://209.145.60.40:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: spa-service
          uri: lb://spa-service
          predicates:
            - Path=/spa/**
        - id: desktop-service
          uri: lb://desktop-service
          predicates:
            - Path=/desktop/**
        - id: movile-service
          uri: lb://movile-service
          predicates:
            - Path=/movile/**
        - id: asp-service
          uri: lb://asp-service
          predicates:
            - Path=/asp/**